### PR TITLE
Optimise images (89 KB reduction)

### PR DESCRIPTION
**Pull request by imageoptimiser**
Hi, b4winckler.

I've taken the liberty of putting macvim's image assets though a range of optimisation tools. Image optimisation allows us to reduce the footprint of images - meaning faster load times at no cost to image quality. It does this by finding the best (lossless) compression parameters, stripping embedded comments, and removing unnecessary colour profiles. [See more](http://port3000.co.uk/imageoptimiser-a-github-bot-to-proactively-op).

I found 62 optimisable images, making a 89 KB reduction in size. That's about 47.55% of your total image assets.

Merry Christmas.

<table><tr><th>Name</th><th>Reduction</th></tr><tr><td>hi16-action-make.png</td><td>18.94%</td></tr><tr><td>hi22-action-make.png</td><td>18.82%</td></tr><tr><td>vim16x16.gif</td><td>14.46%</td></tr><tr><td>vim16x16.png</td><td>14.16%</td></tr><tr><td>vim32x32.png</td><td>14.99%</td></tr><tr><td>vim48x48.gif</td><td>5.75%</td></tr><tr><td>vim48x48.png</td><td>15.82%</td></tr><tr><td>vimlogo.gif</td><td>2.75%</td></tr><tr><td>Advanced.png</td><td>5.43%</td></tr><tr><td>General.png</td><td>3.34%</td></tr><tr><td>startpage.gif</td><td>0.15%</td></tr><tr><td>32x32cancel.png</td><td>13.96%</td></tr><tr><td>AquaTabNew.png</td><td>91.72%</td></tr><tr><td>AquaTabNewPressed.png</td><td>91.64%</td></tr><tr><td>AquaTabNewRollover.png</td><td>91.61%</td></tr><tr><td>AquaTabsBackground.png</td><td>89.62%</td></tr><tr><td>AquaTabsDown.png</td><td>94.73%</td></tr><tr><td>AquaTabsDownGraphite.png</td><td>76.75%</td></tr><tr><td>AquaTabsDownNonKey.png</td><td>83.23%</td></tr><tr><td>AquaTabsSeparator.png</td><td>58.75%</td></tr><tr><td>AquaTabsSeparatorDown.png</td><td>44.70%</td></tr><tr><td>TabClose_Front.png</td><td>43.82%</td></tr><tr><td>TabClose_Front@2x.png</td><td>84.65%</td></tr><tr><td>TabClose_Front_Pressed.png</td><td>46.31%</td></tr><tr><td>TabClose_Front_Pressed@2x.png</td><td>85.90%</td></tr><tr><td>TabClose_Front_Rollover.png</td><td>44.95%</td></tr><tr><td>TabClose_Front_Rollover@2x.png</td><td>85.86%</td></tr><tr><td>TabNewMetal.png</td><td>91.55%</td></tr><tr><td>TabNewMetal@2x.png</td><td>87.36%</td></tr><tr><td>TabNewMetalPressed.png</td><td>91.58%</td></tr><tr><td>TabNewMetalPressed@2x.png</td><td>88.37%</td></tr><tr><td>TabNewMetalRollover.png</td><td>91.51%</td></tr><tr><td>TabNewMetalRollover@2x.png</td><td>88.44%</td></tr><tr><td>Warning.png</td><td>80.63%</td></tr><tr><td>overflowImage.png</td><td>47.66%</td></tr><tr><td>overflowImage@2x.png</td><td>86.62%</td></tr><tr><td>overflowImagePressed.png</td><td>31.23%</td></tr><tr><td>overflowImagePressed@2x.png</td><td>87.55%</td></tr><tr><td>pi.png</td><td>91.49%</td></tr><tr><td>Attention.png</td><td>6.53%</td></tr><tr><td>Copy.png</td><td>33.33%</td></tr><tr><td>Cut.png</td><td>8.88%</td></tr><tr><td>FindHelp.png</td><td>8.74%</td></tr><tr><td>FindNext.png</td><td>13.43%</td></tr><tr><td>FindPrev.png</td><td>15.21%</td></tr><tr><td>Help.png</td><td>2.48%</td></tr><tr><td>LoadSesn.png</td><td>44.03%</td></tr><tr><td>Make.png</td><td>10.32%</td></tr><tr><td>Open.png</td><td>5.49%</td></tr><tr><td>Paste.png</td><td>8.92%</td></tr><tr><td>Print.png</td><td>8.03%</td></tr><tr><td>Redo.png</td><td>4.45%</td></tr><tr><td>Replace.png</td><td>4.63%</td></tr><tr><td>RunCtags.png</td><td>16.07%</td></tr><tr><td>RunScript.png</td><td>5.58%</td></tr><tr><td>Save.png</td><td>4.24%</td></tr><tr><td>SaveAll.png</td><td>2.00%</td></tr><tr><td>SaveSesn.png</td><td>47.98%</td></tr><tr><td>TagJump.png</td><td>5.81%</td></tr><tr><td>Undo.png</td><td>6.02%</td></tr><tr><td>ibeam.png</td><td>34.72%</td></tr><tr><td>vim-noshadow-512.png</td><td>40.26%</td></tr></tr></table>

Tools used: advpng, gifsicle, jpegoptim, jpegrescan, jpegtran, optipng, pngcrush, pngout. This is an automated bot maintained by [@skattyadz](https://twitter.com/skattyadz)

### CODE REVIEW

**Comment by b4winckler** [comment]
Uhm.  Hello?  Am I talking to a robot?

I think your commit message is larger than the amount of space saved by recompressing the images.  Also, thank you for explaining what the benefits of smaller images are.

The above was meant as humor.  Now I must ask seriously: is this pull request a joke/spam?

**Comment by DAddYE** [comment]
BOT: http://port3000.co.uk/imageoptimiser-a-github-bot-to-proactively-op

**Comment by imageoptimiser** [comment]
Sorry for wasting your time, maybe the bot is over-keen. It's only through feedback I can try to make it more useful / scrap it altogether.

**Comment by bikermikem** [comment]
No problem.  Merry Christmas & Happy New Year!

Mike M

**Comment by b4winckler** [comment]
@imageoptimiser: thank you for responding in person.  Getting pull requests obviously not crafted by a human is a bit jarring and my initial reaction was that I thought some company was trying to push their software on me (I'm still not sure if that is the case actually).

On the other hand, I'm sure your scripts can be useful given the right circumstances (i.e. not in the case of this project where there simply aren't that large savings to be made).  However, in my opinion having a bot automatically create pull requests is a bit dubious.  Making people aware of the scripts and letting them run it on their projects themselves is probably a better way to go about it (or open pull requests on projects you care about and craft the request message by hand).

Hope that feedback is of some help to you.

**Pull request closed without merging**
