### PR TITLE
ruby.vim ri balloon function

### PR DESCRIPTION
**Pull request by EricR**
The balloon function doesn't work for a few reasons, and I propose we remove it until we can get a better implementation.
1. "ri -f simple" doesn't work anymore, since simple formatting no longer exists in ri. The balloon will simply show an error.
2. When we do modify ri to work (ie; -f rdoc), the output tens to be very long and the balloon fills the entire screen.

### CODE REVIEW

**Comment by EricR** [comment]
Tends*

**Comment by b4winckler** [comment]
This should be patched upstream (by plugin author, or in core Vim) and not inside MacVim.  This has also been reported in the [issue tracker](http://code.google.com/p/macvim/issues/detail?id=342&q=ruby) and I am still waiting for somebody to push to get it accepted upstream.

**Comment by EricR** [comment]
My bad, got it.

**Comment by b4winckler** [comment]
If the plugin author is not responding then please report this to [vim_dev](http://groups.google.com/group/vim_dev) so that something gets done about this.

**Pull request closed without merging**
