### PR TITLE
Fix missing selector for 10.6 or earlier

### PR DESCRIPTION
**Pull request by splhack**
Hi,

I created a patch for missing selector of 10.6 or earlier. lion branch with Deployment Target=10.6 works fine on 10.6.

### CODE REVIEW

**Comment by b4winckler** [comment]
Thanks for the patch.  However, I believe the correct fix is to only use these APIs if building for 10.7 or higher, so I pushed [another fix](https://github.com/b4winckler/macvim/commit/37741a0cb5f63a0fd10c64dd6e61e6f6ccd00296) instead.

**Comment by splhack** [comment]
I think the lion branch can be build for 10.7, 10.6 or earlier if you use MACOSX_DEPLOYMENT_TARGET with 10.7 SDK. However your fix means that Lion fullscreen feature is only activated with MACOSX_DEPLOYMENT_TARGET=10.7. It doesn't work on 10.6. My fix is, for example, MACOSX_DEPLOYMENT_TARGET=10.6 and if that binary works on 10.7, Lion fullscreen feature is activated, and on 10.6, the former fullscreen feature is activated as well. How about it?

**Comment by b4winckler** [comment]
The patch I pushed does what I initially intended it to, but I admit that I did not consider your point.  I will most likely be rewriting the full screen code so that one can toggle between Lion's and MacVim's full screen code at runtime.  At this point I will make it work the way you suggest.  For now I'll let it be though.

Thanks for pointing this out to me.

**Comment by splhack** [comment]
Thank you so much I really appreciate your work!

**Pull request closed without merging**
