### PR TITLE
Simple commit for doing full screen the Lion way

### PR DESCRIPTION
**Pull request by jxpx777**

### CODE REVIEW

**Comment by b4winckler** [comment]
Ahem.  I was under the impression that Lion APIs are still under an NDA.  Please make sure it isn't or remove this request and resubmit when you are allowed to do so.  Thank you!

**Comment by jxpx777** [comment]
woops… you're right. jumped the gun. I'll remove and keep this to myself for now. D'oh!

**Comment by anaisbetts** [comment]
This is public now, can you reactivate this?

**Comment by b4winckler** [comment]
Native full-screen support was implemented weeks ago...

**Comment by anaisbetts** [comment]
Oops, mea culpa

## 

Paul Betts

SENT FROM MY COMMODORE 64: RESPONSES MAY BE IN ALL CAPS

**Pull request closed without merging**
