### PR TITLE
2x assets for the "new tab", "close tab", "tab overflow" buttons

### PR DESCRIPTION
**Pull request by nico**

### CODE REVIEW

**Comment by b4winckler** [comment]
Is this all the patching that is needed to get the 2x images to show on a hidpi display?

**Comment by nico** [comment]
Yes.

**Comment by b4winckler** [comment]
OK.

I'm a bit worried about the comment "cribbed from Terminal.app".  Does that mean you've included assets taken from Terminal.app?  If so, I have to ask if you are 100% certain that these images are released under a license that lets us use them?  If not, I am not comfortable with merging this patch unfortunately.

**Comment by nico** [comment]
Fair enough. I replaced the images with images drawn by https://gist.github.com/3161796 (which I just wrote).

**Comment by b4winckler** [comment]
Thank you.  I'll try to merge this tonight.

**Comment by nico** [comment]
I rebased this patch so that the assets from Terminal.app don't make it to your repo, even if only for one commit.

**Comment by nico** [comment]
I also added a 2x asset of the overflow chevron.

**Comment by b4winckler** [comment]
Thanks!  I've (squashed and) merged now.

**Comment by nico** [comment]
Thanks!

**Pull request closed without merging**
