### PR TITLE
Fix to draw the underline for inline IM inputs

### PR DESCRIPTION
**Pull request by splhack**
Hi,

I've noticed that MacVim doesn't draw the underline for inline IM inputs when imdisable is set. I created a patch to ignore imdisable flag for it.

### CODE REVIEW

**Comment by b4winckler** [comment]
Thanks.  I'm a bit busy at the moment so it may be a while before I have time to merge but I've put this on my todo list.

**Comment by b4winckler** [comment]
I don't really understand this change.  Can you explain why MacVim have to behave differently from other Vim ports in this respect?  Should this patch be applied to all other ports as well?

**Comment by splhack** [comment]
Because MacVim has the responsibility to render the inline IM cursor, and it should not be affected by imdisable/noimdisable option. However, in the other platform (it means only FEAT_XIM && FEAT_GUI_GTK), it doesn't work with imdisable option, I think.

**Comment by b4winckler** [comment]
Thanks for the explanation and the patch.  In my confusion I did not realize that 'imd' really has nothing to do with whether you are using a different input method or not.  It all makes sense now.

**Pull request merged**
