### PR TITLE
Using floats fails when using a comma-as-a-decimal-separator locale

### PR DESCRIPTION
**Pull request by yanncoupin**
...the decimal separator is a comma

### CODE REVIEW

**Comment by yanncoupin** [comment]
See https://code.google.com/p/macvim/issues/detail?id=511 for more info

**Comment by eirnym** [comment]
@yanncoupin Please, put details here as Google Code shutdown process has begun.

**Comment by yanncoupin** [comment]
@eirnym Do you have a preference for the method? Should I create an issue on github, copying the info from google and somehow link it here?

**Comment by yanncoupin** [comment]
Here's a copy of my original bug report on google code:

**What steps will reproduce the problem?**

Set either language to French or the region to France in the Preferences.

Type the following commands in Macvim's console ( lines prefixed by >> are the answer, E123 are error codes):

```
:let a=0.5
>> E806 + E15
:let a=0,5
>> E806 + E15 + E15
:let a=str2float('0.5')
:let a
>> 0,0
:let a=str2float('0,5')
:let a
>> 0,5
```

_What is the expected output? What do you see instead?_

Here's what I should get:

```
:let a=0.5
:let a
>> 0.5
:let a=0,5
>> E15
:let a=str2float('0.5')
:let a
>> 0.5
:let a=str2float('0,5')
:let a
>> 0.0
```

Note that I was able to get the expected result when I started /Applications/MacVim.app/Contents/MacOS/MacVim from the Terminal with no LC_\* env variables. The problem only exists when the app is started from the finder, the dock or Alfred.

What version of MacVim and OS X are you using (see "MacVim->About MacVim"
and  "Apple Menu->About This Mac" menu items, e.g. "Snapshot 40, 10.5.6
Intel")?

Tested with both snapshots 69 and release 73 (which I hoped would fix the issue), under Mavericks 10.9.4

**Pull request closed without merging**
