### PR TITLE
Refactor/adapt to yosemite

### PR DESCRIPTION
**Pull request by zenangst**
I've added a new tab style that conforms with the new look in Yosemite.

I was wondering what you guys think of it so far?
### On my todo list so far:
- [ ] Change the way the close button looks and behaves
- [x] Change tab bar height
- [ ] Change the "New Tab" icon on the right side
- [X] Change font color depending on tab state - https://github.com/zenangst/macvim/commit/67fb6e662d96a150780b1e97416fee7b8ad70252

screen shot 2014-09-14 at 11 06 35

### CODE REVIEW

**Comment by lucascaton** [comment]
That looks amazing dude, nice job! Congrats!

**Comment by tomekw** [comment]
No idea where to raise this issue but entering the fullscreen doesn't work on Yosemite (/cc @b4winckler)

Top left corner:

http://cl.ly/image/292113231m3L

Bottom left corner:

http://cl.ly/image/120P0M1R122Q

**Comment by maxcountryman** [comment]
@tomekw I'm having the same problem.

**Comment by benoitc** [comment]
@tomekw  @maxcountryman I applied this patch in my repo [1] from the google code tracker [2] as a workaround. It seems to fix most case even if resizing is not that good.

[1] https://github.com/benoitc/macvim/commit/9f77ac3b6b6f9c0eb45f7c4c431db14ea0ea4a1d
[2] https://code.google.com/p/macvim/issues/detail?id=514&start=100

**Comment by eric-wood** [comment]
This is fantastic, really looking forward to this making it upstream! :+1: :+1: :+1:

**Comment by RobertsChou** [comment]
Thank u , good job

**Comment by krid78** [comment]
I compiled and testes the version ([zenangst/macvim](https://github.com/zenangst/macvim)). The issue with missing top lines when only one tab is open at full screen mode is still there.

regards

**Comment by jordwalke** [comment]
:+1:

**Comment by vestimir** [comment]
Looks great. :+1: 

offtopic: @krid78 @benoitc @tomekw About the blank lines there's a fix in progress here - https://github.com/b4winckler/macvim/pull/48

**Comment by mikekreeki** [comment]
:+1:

**Comment by eirnym** [comment]
:+1:

**Comment by luishdez** [comment]
Awesome work! 

I will add these extras to the tasks

[ ] Use hover native scrolls ( invisible ones )
[ ] Dark mode for yosemite

**Comment by UrsaDK** [comment]
:thumbsup:

**Comment by zenangst** [comment]
Hey folks, thanks for your support and enthusiasm. Kinda swamped at work right now but this is on my todo-list... and I would love to finish pully.

**Comment by vestimir** [comment]
@zenangst what do you mean by 

> Change the way the close button looks and behaves

PS: Great job so far! :dart:

**Comment by christianparpart** [comment]
hey guys. is there an update on this so far? or got it suspended?

**Comment by simono** [comment]
I don't think this repository is active anymore. https://github.com/b4winckler/macvim/pull/44#issuecomment-78869349

**Comment by jean-io** [comment]
Hi,

This repo is no longer active, however this one is: https://github.com/macvim-dev/macvim

Any chance you could update it?

**Comment by mikekreeki** [comment]
Would be very cool :+1:

**Comment by jordwalke** [comment]
This would be really awesome to have. Any chance you could submit the pull request to the new official repo at https://github.com/macvim-dev/macvim ? That repo is fairly active now and I'm hoping there will be some people excited to take a closer look at your PR.

**Comment by splhack** [comment]
I've revised this pull request in https://github.com/macvim-dev/macvim/pull/193, now you can improve and send pull requests for `feature/yosemite-tab-style` branch of https://github.com/macvim-dev/macvim.

**Pull request closed without merging**
