### PR TITLE
Changed the capitalization in the menus

### PR DESCRIPTION
**Pull request by ggustafsson**
Fixed the capitalization in all menu entries to make MacVim's menus look
consistent and fit in with all other applications on Mac OS X.

Most of what i did was uppercase a few characters. Except when it comes
to "Toggle Full Screen Mode", i changed it to "Toggle Full Screen" since
all other applications use "Enter Full Screen" and "Exit Full Screen".

I also had to change "Check for updates..." to "Check for Updates..." in
MainMenu.nib. This also seems to have deleted two files? All i did was
open the file in Xcode, change the text and save it.

I can have missed something but i think everything is as how it should be.
Enjoy! :)

### CODE REVIEW

**Comment by ggustafsson** [comment]
Also, maybe we should change Syntax -> "On/Off for This File" to "Toggle for This File". Just noticed it. It would fit with how it works with full screen for example.

**Comment by b4winckler** [comment]
Thanks!

It is nice that you did this, but I am not sure whether to merge it or not as some of the changes are to parts that come from the official Vim distribution and as such should be changed by upstream (if at all).  Also, these menus are translated, so maybe more than the English translations would have to change?

On the other hand I've already changed the menus around and MacVim currently doesn't support the non-English translations, so maybe it makes sense to merge this.  I'm not sure.

If you were to send me a patch that only affects the MacVim-specific changes to menu.vim I wouldn't hesitate to merge your changes (they are inside "if has('gui_macvim') ...").  As it is, I'm on the fence...

**Comment by ggustafsson** [comment]
This is as good as it will get in this case. Does the other stuff change things in gvim? Is there other gui front ends?

The best fix i can think of is having a simple script that uses sed to change the letters. That way one could easily keep the file up to date with Vim changes. The file is probably rarely touched anyway. We already know all the characters that is wrong so if Vim changes and sed misses something it doesn't matter and it doesn't matter if they add something new that sed misses because we can easily edit the script for that.

**Comment by b4winckler** [comment]
Nah, it is probably easier to just change the files and handle any merge conflicts.  It is true, like you say, that the menu files hardly ever change.

Let me think it over for a bit.  Maybe I'll just merge your fixes to all menus.

On a related note: I have for a long time wanted to completely overhaul the menus so that they are actually useful.  At the moment I think there are way too many items in there and it is not clear how to find them.  Another thing I can think of that I don't like is the fact that there are "settings" under the "Edit" menu -- that is very weird for a Mac app.  Also, some items on e.g. the "Window" menu should probably be under a "View" menu...anyway, I digress.

**Comment by ggustafsson** [comment]
Must be hard to decide what should and shouldn't be in the menus. It is Vim after all. If i were you i would see if i couldn't find a few people that have been using OS X and preferably MacVim for a long time and ask if they want to help out. I don't even use the menus myself. Honestly, if it weren't for the slow scrolling in Terminal.app i would never have touched MacVim in the first place.

**Comment by eddiemonge** [comment]
any thought on this?

**Comment by Crazor** [comment]
The menus should be changed to reflect the structure in other Mac apps. I guess Apple's HIG have a stance on the menus as well.

I for one never use MacVim's menus, because they are kind of broken in many ways and I never find anything. Also I think there are many useless items (Syntax test stuff, most of the settings in the edit menu [they don't persist, so I have to learn about what goes into my .vimrc anyway], etc.)

**Pull request closed without merging**
