### PR TITLE
Addressed issue with ruby.vim filetype plug-in

### PR DESCRIPTION
**Pull request by Goles**
- Updated ruby.vim filetype plugin to address the ussage of deprecated ruby functions.
      \* Issue described here http://stackoverflow.com/questions/9590658/vim-e854-path-too-long-for-completion/9594727#9594727
  _NG

### CODE REVIEW

**Comment by b4winckler** [comment]
Thank you for taking the time to write and submit this patch.

Unfortunately you have sent it to the wrong place -- all patches to plugin files should be sent to the respective plugin author (email is listed at the top of the patch).

**Comment by Goles** [comment]
I understand,

However it seems that this issue has been adressed in ftplugin but MacVim may be using an outdated version ? Can't seem to find the original ftplugin repo, but at least [Vim-Ruby](https://github.com/vim-ruby/vim-ruby) seems to be using the updated [ruby.vim](https://github.com/vim-ruby/vim-ruby/blob/master/ftplugin/ruby.vim). 

Cheers.

**Comment by b4winckler** [comment]
I don't know the answer to your question but I pushed the latest upstream changes yesterday, so the master branch has the latest version (as of this writing).  I don't know whether upstreams (i.e. the original Vim repository) has the latest version yet though...

**Comment by Goles** [comment]
That could be the issue,  

Maybe I should report the issue there.  

## 

Nicolas Goles
Mobile # +56 9 91591989
Twitter @ngoles

**Comment by steveno** [comment]
As someone who maintains a set of plugins for a language usable within Vim I can tell you that generally the process goes something like this:

1) If you're not the maintainer you ask the maintainer to accept your patch.
2) The maintainer then emails the patch to Bram
3) Bram then pushes you patch into the main mercurial repository

Step 3 by the way may take some time. Bram likes to group his commits so if he accepts your patch it might be a week or two before it actually gets pushed.

I get emails asking me to update my language plugin probably about once a month or so.

**Pull request closed without merging**
