### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by kaishin**
I love MacVim, but I think the current icon is starting to show its age. I've designed this and used it locally for a while.

icon_512x512

### CODE REVIEW

**Comment by kaishin** [comment]
I just realized that `vim-noshadow-512.png` is used to generate the document icons. I spent some time making a pixel-precise generic icon (using the large graphic on small versions gives a blurry result) but I have no idea how the current script works or how I can update it to ignore that file and just append the extension string at the bottom of the icon...

**Comment by kaishin** [comment]
I uploaded a no-shadow version.

**Comment by ghost** [comment]
May consider doing a "flat" style icon, since OSX yosemite has a metro-like flat icon style etc.

**Comment by kaishin** [comment]
@prophittcorey The effect can be toned down, but Yosemite icons are not totally flat. See Mail.app and Messages.app, among others.

**Comment by kaishin** [comment]
@b4winckler Any chance of getting some feedback on this?

**Comment by james2doyle** [comment]
I am using this for my MacVim already. If no one here wants it, you should check out the [VimR project](https://github.com/qvacua/vimr). He might be interested in a new icon since there is no default one.

**Comment by amw** [comment]
I really love this icon by Drew Yeaton. That's what I've set my MacVim to use.

https://dribbble.com/shots/337065-MacVim-Icon-Updated?list=users&offset=9

**Comment by james2doyle** [comment]
That icon is being used by the [VimR Project](https://github.com/qvacua/vimr/issues/47)

**Comment by amw** [comment]
Not sure if that's a problem. Icon was not created for VimR project specifically and we would probably get Drew's permission to use it for MacVim as well. Would only confuse those who have both apps installed, which I assume is not that many people.

**Comment by james2doyle** [comment]
I know that the VimR guy is going to have that icon tweaked to look better for Yosemite, right now it is that exact one. There is small likelihood that they will clash or be the same. It was more of a heads up.

**Comment by lucascaton** [comment]
As OS X Yosemite is coming with a new "flat" design I believe we should follow the same pattern in the new icon ツ

**Comment by jasonlong** [comment]
Here's a Yosemite version I put together. Happy to polish it up if you guys want to use it.

screen shot 2014-08-20 at 8 41 06 am

**Comment by amw** [comment]
My vote is still with the icon by Drew Yeaton. I've been using it on my Yosemite install and it fits nicely too.

**Comment by kaishin** [comment]
@jasonlong  like the spirit of this, but I'm not sure about the circle though. The V doesn't fit in there (too much space to its right) and circle icons are not recommended for text editors.

@amw That doesn't scream Vim to me as the capital V does.

I'm not trying to defend my original icon—it clearly needs some tweaks for Yosemite—but if this is going anywhere, we need to make sure that we end up with something better than what we have now.

Also, no collaborator/owner have chimed in yet.

**Comment by amw** [comment]
@kaishin it does say "vi". "vi" screams Vim to me even more than just capital V ;-)

Take a look on my Yosemite app switcher.

vim-switcher

**Comment by jasonlong** [comment]
> circle icons are not recommended for text editors.

According to whom?

Also, I've gotta say that I don't think an icon based on TextMate's 2004 icon is the way forward here.

**Comment by PixelJanitor** [comment]
_Grabs Popcorn_

**Comment by caiogondim** [comment]
@jasonlong Do you have a link to your icon? Would love to use in my current MacVim

**Comment by jasonlong** [comment]
@caiogondim I'd like to make some tweaks to this one first. I'll drop a link here when I do.

**Comment by jwmann** [comment]
I like the direction @jasonlong is heading with the icon. Seems to fit more with the Yosemite styling than the Vi TextMate style icon. Still, it could use a bit more tweaking as you mentioned yourself.

**Comment by jasonlong** [comment]
Here's another take using the classic logo and Yosemite styling. I rounded the corners of the V to soften it a bit.

screen shot 2014-08-22 at 11 32 00 am

**Comment by jwmann** [comment]
I definitely like the approach of this revised version. It seems more of an evolution of the previous logo in order to match the new aesthetic of Yosemite.  
I would like to see a little bit more contrast in [this area](http://d.pr/i/s88M/57IcVg4k) but that might be just because of the compression/size of the jpg playing with my eyes.

**Comment by jasonlong** [comment]
@jwmann Good call. This version improves that edge and shows the icon in the context of some other Yosemite icons.

screen shot 2014-08-22 at 2 50 54 pm

**Comment by jwmann** [comment]
Very nice! Great job @jasonlong :+1: 
Hopefully everyone likes it as well and a Project Collaborator merges in the new Icon :)

**Comment by geetarista** [comment]
:+1:

**Comment by caiogondim** [comment]
@jasonlong Loved that new iteration.

**Comment by DomT4** [comment]
This looks great in the dock alongside other Yosemite icons. Big :+1: from me.

**Comment by jasonlong** [comment]
I've created a pull at #44 with this proposed icon. I'm not sure if/when this will get merged, but feel free to grab it over there if you'd like to use it now.

**Comment by kaishin** [comment]
@jasonlong 

> According to whom?

To me. There are no rules set in stone (I used 'recommended'), but a closer examination of the default app icons in Yosemite (http://martiancraft.com/blog/2014/07/inspecting-yosemite-icons/#the-shape-hierarchy) as well as a look at all document-based OS X apps from the last decade points to that.

In any case, I'm closing this due to irrelevance. There's been no input from the owners and I no longer use MacVim in favor of Terminal/tmux.

**Comment by jdsimcoe** [comment]
@jasonlong Do you have a link to the ICNS and source files for this icon you created?

screenshot

**Comment by jwmann** [comment]
@jdsimcoe I think what you're looking for is referenced here - https://github.com/b4winckler/macvim/pull/44

_EDIT:_
Whoops, I see now that you meant the older version of the icon. Nothing to see here haha

**Comment by jdsimcoe** [comment]
@jwmann yeah thanks I have those too, I like this specific one for personal use.

**Comment by jasonlong** [comment]
@jdsimcoe I can't seem to find that file on my computer. I can probably recreate it pretty easily though if you like.

**Comment by jdsimcoe** [comment]
If it isn’t a big deal, otherwise it’s ok.

**Pull request closed without merging**
