### PR TITLE
Update app and document icon for Yosemite

### PR DESCRIPTION
**Pull request by jasonlong**
**[Download the .icns file](https://github.com/jasonlong/macvim/blob/024f6d4395c3e2f873e020cdddd7f3d22d05166a/src/MacVim/icons/MacVim.icns?raw=true)** (**Update:** this is the updated version from [below](https://github.com/b4winckler/macvim/pull/44#issuecomment-53358877))

This is the icon I proposed in #41. I have created a new .icns file with slightly tweaked versions at `512@2x`, `256@2x`, and `128@2x`. Smaller versions will scale down using the `128@2x` version.

This is the `128@2x` version:

icon_128x128 2x

I also updated the document icon.

Before:

macvim-generic-old

After:

icon_512x512 2x

### CODE REVIEW

**Comment by leonardt** [comment]
:+1:

**Comment by agsdot** [comment]
Nice!

**Comment by oleyb** [comment]
This is sooo good.

**Comment by DomT4** [comment]
I commented on the other thread too, but a :+1: from me. It looks great alongside the other Yosemite icons. Hope this one gets merged.

**Comment by EduardoBautista** [comment]
:+1:

**Comment by khzaw** [comment]
:+1:

**Comment by caiogondim** [comment]
:+1:

**Comment by bruno-** [comment]
Really nice :+1:

**Comment by joshhartigan** [comment]
:+1:

**Comment by jojoyuji** [comment]
:+1:

**Comment by porada** [comment]
:+1:

**Comment by divanvisagie** [comment]
:+1:

**Comment by zenangst** [comment]
:+1:

**Comment by bolasblack** [comment]
:+1:

**Comment by natw** [comment]
I'm not loving the low contrast.  The V, especially in the upper left, starts to fade into the background. It's certainly more Yosemite-ish, and probably even better looking, but not nearly as iconic.

**Comment by rricard** [comment]
:+1:

**Comment by fatih** [comment]
:+1:

**Comment by evantravers** [comment]
:+1:

**Comment by jojoyuji** [comment]
@natw  I disagree, it fits perfectly in my yosemite context. Contrast is good too :)

**Comment by mdznr** [comment]
The shadow is a bit wonky. It's not soft and is just offset vertically. This won't work super well alongside other app icons. The shadow form the 'V' can be sharper against the diamond, but not against the background.

The styling of the shapes (inner shadows) feels strange and would work better if removed, especially when the icon is scaled down.

The serifs on the 'V' shape are extremely rounded, creating a fully rounded end-cap, which is highly unusually for a typeface and distracting because of it.

If you're using a green color close enough to the ones used on Apple's own iOS and OS X apps, just use the same exact color(s), otherwise it creates inconsistency and dissonance.

The icon I've proposed in #43 solves some of these issues. I started working on that icon before even realizing there were discussions about it.

Shown below is the 128x128 version of the icon I've proposed.
icon_128x128

**Comment by jasonlong** [comment]
@mdznr I have to say I disagree with most of this. The shadows are cast vertically because the light source of Yosemite icons is directly above. The inner and outer shadows here match up very close to the reference Yosemite icons I have, as do the gradients. I've tweaked the shadows at the smaller sizes in my .icns. And I definitely don't agree with using the exact same green that Apple is using for their icons.

**Comment by mdznr** [comment]
@jasonlong 

Sorry, I should've been more clear. Yes, the shadow will still cast down vertically, but it should be blurred more. Right now it is very sharp (not a lot of depth between the shape and the background). This is not how the other app icons (especially Apple's) are.

The inner shadows are several pixels thick and are very dark and very light. This is not how they appear on the Yosemite icons. 
screen shot 2014-08-25 at 4 19 08 pm

Not every icon needs to be limited to the small color palette, yes. However, the green shown above is treading too close to the standard green Apple is using. If you don't wish to use that green, move further away from it, otherwise it looks and feels like a mismatch and not a deliberate choice.

**Comment by jasonlong** [comment]
Ok, I took a closer look at the shadows and made some tweaks. I think these are looking better do indeed match the reference icons better.

icon_256x256

icon_128x128 2x

I still don't buy the green argument (and I'm pretty fond of this color). There are going to be a zillion green app icons all over the spectrum, including shades of light green. I don't believe that there should be some value where icon colors should "snap" to Apple's lime green.

**Comment by ghost** [comment]
awesomesauce :+1:

**Comment by fgr0** [comment]
Awesome icon! I just wanted to ask, if someone could also generate the custom-filetype-icons using this design. The scripts to generate them haven't worked for me since Mountain Lion :(

**Comment by brianherman** [comment]
Love it!

**Comment by jasonlong** [comment]
@laerador Ah, I was wondering about that. In the source, all of the custom filetype icons are symbolically linked to the generic one. I didn't realize there was a script that could potentially do it. I'd be up for working on that, but before doing much more here, it would be nice to know whether or not this design is likely to be accepted.

@b4winckler Any thoughts here?

**Comment by nerdyjem** [comment]
@laerador I've got a set generated from the updated icon here, all 512px: http://girlintroverted.wordpress.com/2014/08/15/filedoc-icons-for-macvim/
Direct link: https://dl.dropboxusercontent.com/u/9401664/mac%20stuff/macvim_docicons_jasonlong.zip

**Comment by fgr0** [comment]
@jocelynmallon this is awesome, thanks! Would you mind sharing how you generated them? Manually or with the makeicns script?

@jasonlong [Building - b4winckler/macvim](https://github.com/b4winckler/macvim/wiki/Building#notes-on-document-icons) shows the steps of building custom filetype icons with the filetype-name inside the icon. Makes it very easy to distinguish between e.g. Header-Files and Source-Files.
But the script hasn't been working (for me) since Mountain Lion. You can find some information about the error i encountered [here](https://groups.google.com/forum/#!msg/vim_mac/-aTaGvnI2KU/k_JwNTs0TskJ), if you are interested in fixing the problem.

**Comment by nerdyjem** [comment]
@laerador I used the included macvim script with a few changes, maybe I'll throw up a blog post since it took a few changes to make it work on Mavericks.

In short though, you need a 512px version of "GenericDocumentIcon.icns" along with a precompiled "makeicns" binary.

EDIT: made a blog post with my changes here: http://girlintroverted.wordpress.com/2014/08/26/macvim-doc-icons-redux-howto/

**Comment by jasonlong** [comment]
Very cool, thanks @jocelynmallon!

**Comment by kaishin** [comment]
I'm in favor of merging this too, hopefully.

**Comment by mdznr** [comment]
This still needs work.

The inner shadows are still incorrect. There basically aren't inner shadow effects on Apple's Yosemite icons but these are extremely contrasting and jarring.

The drop shadows are still incorrect (hint: more than one is used for the outline of the total shape). If the "V" is stacked on top of the diamond, there should be a shadow that appears on the diamond from the "V" and a different shadow that the "V" casts onto the background.

I would also strongly suggest removing some of the rounded corners on the "V" shape as most normal typefaces do not do this.

**Comment by kaishin** [comment]
@mdznr I don't totally disagree. You are making some valid points. But I think this dragged too long and I'd rather see the icon suggested above merged first before any further enhancements are made.

I saw you already opened a PR as well. I think if anything this just lowers the chances of any PR to get merged. I closed my original PR in favor of this. It would be nice if we could get this merged then provide the source files for others to make further enhancements. 

If we gotta do this the proper way, it'd better be 100% in the open.

**Comment by DomT4** [comment]
There are actually inner shadows on Yosemite's icons. This is particularly evident if you take a look at the Facetime Icon closely, where you can see the main part of the 'camera' casts a shadow downwards.

I don't think there's actually a need to get the icon perfect first time. It's not uncommon these days for icons to be slightly tweaked between other updates, and I don't think it'd be an awful thing for MacVim to adopt if necessary. 

I've been with Yosemite since DP1 and the situation with Apple-provided Yosemite-style icons is fluid enough as is; trying to settle on some definitive style before they've finished ironing out the design kinks is probably jumping the gun a tad.

I think @jasonlong has done a very decent amount of work on this, and taken on board a lot of your original comments. Nobody is going to get the icon completely perfect to everyone's taste the first time around. Nobody is suggesting that we merge this and then forget about it.

**Comment by mdznr** [comment]
@DomT4 Yep. There are. However, you mentioned you need to look closely to see them. The ones on this icon are very apparent. I said "there basically aren't", which means it's closer to nothing than strong inner shadows.

> Nobody is going to get the icon completely perfect to everyone's taste the first time around

Nope. That's why I'm currently giving feedback for improvements. Why wait until later when I can just give them now as I see them?

@kaishin 

> I'd rather see the icon suggested above merged first before any further enhancements are made.

Yosemite isn't released yet, so there isn't a real rush to get this merged. It's scheduled for release in the Fall. I also like to see "do it once, do it right". I find it would be very strange to ship several versions with modifications of the icon.

> I saw you already opened a PR as well.

Yep, I quickly put one together before even realizing there was another request open.

> If we gotta do this the proper way, it'd better be 100% in the open.

Not sure what you mean here. This thread is in the open, isn't it? What are you referring to that isn't "open"?

**Comment by kaishin** [comment]
> Not sure what you mean here. This thread is in the open, isn't it? What are you referring to that isn't "open"?

I'd like for whomever working on this to provide the PSD, SVG, Sketch whatever they are using for future enhancements.

**Comment by kaishin** [comment]
@mdznr Oh and "do it once, do it right" has no place in design ;)

**Comment by mdznr** [comment]
@kaishin Mmm... yes. Should that be included in the repo or elsewhere?

If you're working towards a goal (a particular major release), then don't leave outstanding known enhancements. An icon is a special subset of design, like a brand. I can't recall the last time I saw a brand iterating on their logo/identity in public.

**Comment by DomT4** [comment]
@mdznr It depends heavily on how you use OS X's dock. If you turn the magnification element off, then sure, the shadow is much more subtle. If you use magnification though, the shadow can tend to feel like it's trying to smack you in the face. I'm hesitant to make any presumptions about how people configure their docks.

I appreciate that you're trying to offer improvements where you see them, but I'm fearful of having this design debate in a bubble. Even with 28 participants we're only touching the bare minimal edge of users of MacVim, and at some point I'd like to get the new icon out to a wider user base and get feedback on it that way. If we keep this bubbling along here for too much longer it risks getting bogged down and this going nowhere at all, which is something I'm quite wary of. (_Development hell & all that_).

**Comment by kaishin** [comment]
@mdznr They can be in the repo, or self-hosted by the author if the owner doesn't want them around.

Calling those changes 'outstanding' is debatable, but open-source software is better exactly because it can afford to iterate in public.

**Comment by DomT4** [comment]
> I can't recall the last time I saw a brand iterating on their logo/identity in public.

There was an almost identical discussion to this over at Github's Atom the other week, and another over at iTerm2. In the world of open-source, icons are much more heavily discussed in public than people appreciate.

**Comment by nerdyjem** [comment]
@mdznr if you want, here's a set of doc icons to go with the icon you posted in https://github.com/b4winckler/macvim/pull/43

https://dl.dropboxusercontent.com/u/9401664/mac%20stuff/macvim_docicons_mdznr.zip

**Comment by mhumeSF** [comment]
:+1:

**Comment by MarioRicalde** [comment]
:+1:

**Comment by benwoodward** [comment]
:heart:

**Comment by kaishin** [comment]
@b4winckler Any chance of getting this looked at? It would be nice to provide some feedback so that we can move forward with this.

**Comment by vestimir** [comment]
:+1: from me, too.

**Comment by rgrinberg** [comment]
+1

**Comment by nifoc** [comment]
:+1:

**Comment by bendoh** [comment]
:+1:

**Comment by marcelofraga** [comment]
:thumbsup:

**Comment by ponyta** [comment]
:+1:

**Comment by jnthnclrk** [comment]
:+1:

**Comment by flippidippi** [comment]
:+1:

**Comment by lxyu** [comment]
:+1:

**Comment by nico** [comment]
(The original document icon was created with https://code.google.com/p/docerator/ , which lets the page curl shadow fall on top of the app icon.)

**Comment by rgrinberg** [comment]
:+1:

**Comment by gabrielrinaldi** [comment]
:+1:

**Comment by wridgers** [comment]
I'd also like to see this move forward. :+1:

**Comment by nburns** [comment]
:+1:

**Comment by jaredculp** [comment]
:+1:

**Comment by jasonlong** [comment]
Kinda seems like this repo has been abandoned. :crying_cat_face:

**Comment by DomT4** [comment]
@b4winckler is the one to ask. He was last around 12 days ago or so.

**Comment by divanvisagie** [comment]
@jasonlong This time of year can be crazy for some people. Maybe he will get back to it after the silly season

**Comment by jasonlong** [comment]
@divanvisagie Yeah, for sure. But this PR has been open for 3 months w/ zero feedback despite strong approval from the community.

**Comment by eirnym** [comment]
:+1:

**Comment by ghost** [comment]
Good idea, this is a nice icon!

**Comment by shaond** [comment]
@jasonlong and others, I'm sure the VimR (@qvacua) project would appreciate your icons and bug fixes: 
https://github.com/qvacua/vimr

**Comment by eirnym** [comment]
@shaond Why fork? Why we should spread our forces?

**Comment by DomT4** [comment]
@eirnym VimR isn't really a fork in the traditional sense. It's an interesting project, but doesn't really share the same userbase as MacVim or Vim does.

**Comment by jarinudom** [comment]
:+1:

**Comment by shaond** [comment]
Folks, @jocelynmallon has done a fine job of merging all these pull requests and documented how to install it on her blog: https://girlintroverted.wordpress.com/2014/11/06/macvim-for-yosemite/

It's worth checking out. Kudos go to @jocelynmallon (you rock!). 

update_app_and_document_icon_for_yosemite_by_jasonlong_ _pull_request__44_ _b4winckler_macvim

**Comment by gglanzani** [comment]
@shaond :+1: 

Great work @jocelynmallon

**Comment by eirnym** [comment]
:+1: I like this icon

**Comment by ViViDboarder** [comment]
@jasonlong did you submit this via mailing list? I'm not sure that @b4winckler monitors this repo here. Maybe soon now that Google Code is shutting down.

**Comment by simono** [comment]
I don't know if this repository is monitored at all. See https://groups.google.com/forum/m/#!topic/vim_mac/-bd5RKGs8qw and https://github.com/macvim-dev/macvim

**Comment by jasonlong** [comment]
Thanks for the heads-up @simono. I'll submit a PR over on @macvim-dev's repo.

**Comment by ghecho** [comment]
:+1:

**Comment by johnstephens** [comment]
I love it! What a delightful surprise when I ran `brew upgrade` today.

**Comment by jtheoof** [comment]
Yeah, @johnstephens  is right! So the new icon is there, but the MR is still opened. What kind of magic happened here?

**Comment by simono** [comment]
@jtheoof see https://github.com/macvim-dev/macvim/pull/1

**Comment by jasonlong** [comment]
Going to close this. For those interested, the icon is now available in https://github.com/macvim-dev/macvim which is what homebrew uses now.

**Pull request closed without merging**
