### PR TITLE
Noted --help param to reduce initial confusion

### PR DESCRIPTION
**Pull request by timoxley**
I spent a few minutes trying to figure out where the params were documented. only after I played around with it and read some other docs did I discover this flag. Thanks.

### CODE REVIEW

**Comment by b4winckler** [comment]
Thanks.  Can you please (hard) wrap the text to 78 columns and remove the empty line before the "e.g."?  That way I can just automerge this pull request.

**Comment by timoxley** [comment]
:D

**Comment by b4winckler** [comment]
Sorry for being a pain on such a small pull request, but I'd really appreciate it if you would make it into one commit and [shorten the commit message](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).  Thanks.

**Comment by timoxley** [comment]
No worries

**Comment by b4winckler** [comment]
Thanks.

**Pull request closed without merging**
