### PR TITLE
Support Emoji

### PR DESCRIPTION
**Pull request by splhack**
- Added 'E' option into guioptions. 'E' option enables to render Emoji characters using 'Apple Color Emoji' font in MacVim. 'E' option is not set in default, so it doesn't change the current behaviour of MacVim.
- Changed the range of double wide characters for Emoji. From U+1F000 to U+1FFFD. Ref. http://en.wikipedia.org/wiki/Emoji

### CODE REVIEW

**Comment by zhaocai** [comment]
tried it. very nice :+1:

**Comment by b4winckler** [comment]
Thanks, this looks interesting!

You seem to also fix some rendering problems with surrogate pairs -- is that right?

Otherwise, why exactly does so many lines of code need to change?  I don't know anything about the intricacies of supporting Emoji, but my naive thought was that all that should be needed is another font.  Would you mind explaining it to me?

The thing that makes me hesitate is that this patch touches the Vim code, and more importantly that it adds an option (the `E` flag in `guioptions`).  This makes me think that the patch should first be submitted to mainline Vim.  Have you tried getting any feedback from Bram on this?

Oh, and by the way, I just pushed a commit that messes around with `MMCoreTextRenderer.m` so unfortunately this patch will not apply at the moment.  Sorry about that.

**Comment by zhaocai** [comment]
@splhack can you update the patch? thanks :)

**Comment by splhack** [comment]
updated. got rid of 'E' guioptions(i had added it for keeping the current rendering font API because I was too worried about changing the rendering font API so far).
- Changed the range of double wide characters for Emoji. From U+1F000 to U+1FFFD. Ref. http://en.wikipedia.org/wiki/Emoji
- Using 'Apple Color Emoji' font for rendering emoji with NSFontDescriptor -fontDescriptorByAddingAttributes:
- Fixed rendering for Surrogate pair chars, CTFontGetGlyphsForCharacters returns 0 for Surrogate high char glyphs

**Comment by bwiggs** [comment]
+1

**Comment by amadeus** [comment]
This patch currently has a bunch of merge conflicts, I think mostly around Mavericks changes. Anyway this can get fixed up to work on the latest?

**Comment by splhack** [comment]
@amadeus Have you tried the latest my patch? I already updated my patch for the latest master branch.

**Comment by amadeus** [comment]
@splhack Is there a place where the patch is hosted? I've been attempting to apply from this PR branch.

**Comment by splhack** [comment]
@amadeus github. https://gist.github.com/piscisaureus/3342247

```
git checkout -f master
git merge origin/pr/38
```

**Comment by amadeus** [comment]
That worked, thanks!

**Comment by afh** [comment]
:+1:

**Comment by amadeus** [comment]
Noticing some emoji don't seem to work:

example

**Comment by splhack** [comment]
How about the additional patch?

```
diff --git a/src/mbyte.c b/src/mbyte.c
index f4ce198..2ed8d75 100644
--- a/src/mbyte.c
+++ b/src/mbyte.c
@@ -1243,7 +1243,10 @@ utf_char2cells(c)
    {0x1100, 0x115f},
    {0x11a3, 0x11a7},
    {0x11fa, 0x11ff},
-   {0x2329, 0x232a},
+   {0x2300, 0x23ff},
+   {0x2700, 0x27bf},
+   {0x2b00, 0x2bff},
+   {0x2e00, 0x2e7f},
    {0x2e80, 0x2e99},
    {0x2e9b, 0x2ef3},
    {0x2f00, 0x2fd5},
```

**Comment by amadeus** [comment]
Yup, that seemed to fix those particular emoji.

**Comment by jm3** [comment]
Would be great to see this PR make it in :)

**Comment by skalnik** [comment]
Yes please! :+1:

**Comment by lsloan** [comment]
:shipit: Can't wait to see this in a MacVim release.

**Comment by kfix** [comment]
I hate pile-on comments, but its ~50 whole lines of code, finely aged in a PR cellar for 2 years, so ...
:shipit: :+1: :neckbeard: :boom: 
[VimR](http://github.com/qvacua/vimr) uses MacVim too.

**Comment by iferguson90** [comment]
Hello everyone. :sparkles: This repo is no longer actively maintained. The repo you're looking for is [macvim-dev/macvim](https://github.com/macvim-dev/macvim). See also this [discussion](https://groups.google.com/forum/m/#!topic/vim_mac/-bd5RKGs8qw) and the Google code [project page](https://code.google.com/p/macvim/) (which now links to the new repo).

**Comment by kfix** [comment]
Thanks @iferguson90.
So, in your opinion, should this be sent to vim-dev@? Or vim-mac@? Or vim-multibyte@? They all seem applicable!

I guess the mbyte.c bit should be upstreamed to Vim mainline, and then the Cocoa bits can be put to macvim. hopefully :four_leaf_clover: vim.org [will choose](https://groups.google.com/forum/#!msg/vim_dev/ehzfCDccmek/PU1sTZNdsTUJ) to move their code from Hg@google to git$FOO this year, so this might become easier.

**Comment by bendoh** [comment]
+1 – It's been a while since we've seen some action on this!

**Comment by kfix** [comment]
https://github.com/vim/vim is taking pull requests now.

**Pull request closed without merging**
