### PR TITLE
Alloy's native sidebar fork, updated to match latest snapshot (68)

### PR DESCRIPTION
**Pull request by rcarmo**
Hi there. I've gone through alloy's split-browser branch, and the merge was remarkably clean and worked first time. Everything seems to be in order - the behavior's the same as I have on another machine with his (now unavailable) binaries.

### CODE REVIEW

**Comment by b4winckler** [comment]
Sorry, I'm not going to merge this into mainline -- I have discussed the reasons why elsewhere at length.

**Comment by rcarmo** [comment]
Okay, so I'll probably keep maintaining it for as long as I need it.

I'd really like to know the reasons, though. This was a stupefyingly easy patch, and alloy's code seems mostly OK.

R.

**Comment by b4winckler** [comment]
You'll have to look through the vim_mac Google group archives for an answer.

**Comment by b4winckler** [comment]
For future reference, here is the link to the thread where I outline why this branch is not ready to be merged:

https://groups.google.com/d/msg/vim_mac/iH9my4jv5WI/SdmApzZ8Ru0J

**Comment by rcarmo** [comment]
Okay, I get your point. Nevertheless, I find this stupendously more useful and productive than NERDTree, which I find unwieldy, buggy and counterintuitive -- but that's beside the point here (I've long since replaced _that_ with ctrl+p).

Putting aside code structure, I have no issue with the way it's integrated nor with fragmentation, really.

It has to be said that even though I spend 90% of my time using vim on servers with Pathogen to run herd on a dozen or so hand-picked plugins (that work exactly the same on every platform I use, sure -- so I get your point), I _still_ prefer having this on my Mac, because it is such a tremendous improvement on user experience. And I don't even keep it open all the time - I just want something that shows me regular, _native_ icons when I'm looking for a file.

I think the Mac environment is different enough to deserve something like this, and consider it as much of a necessity as native tabs, menus and the preferences dialog.

**Pull request closed without merging**
