### PR TITLE
Patch for Issue#299

### PR DESCRIPTION
**Pull request by humblehacker**
I added a configure option --enable-envycoder which is off by default.  I also modified make_icons.py so that it would gracefully fail if the font was not found.

This is probably not the best solution, but it gets around builds failing on a clean checkout when damieng.com is down.

### CODE REVIEW

**Comment by b4winckler** [comment]
Thanks for the patch but unfortunately it does not work.  It now never downloads the Envy Code R font, even if the --enable-envycoder switch is given.

When testing your patch I think you need to do "make clean" inside MacVim/icons in between tests in order to really test it.

Do you think you can fix it?

Maybe instead of a switch to configure, is there a way to only use the Envy Code R font if it is in the folder?  Perhaps with a target in the Makefile to "get Envy Code R" that I can manually run when building snapshots etc.  This may be easier than messing around with the configure script (in my attempts the AC_DEFINE in configure never "reached" the icon Makefile).

**Comment by humblehacker** [comment]
Yes, I realized my mistake when I woke up this morning. Sorry to waste your time with it. I can fix it, but perhaps an even better solution would be not to depend on a font that can't be redistributed (I assume that's why it's downloaded).  Why not instead depend only on fonts already on OS X or a font we can check into the repo.  I see "Menlo Regular" hard coded into gui_macvim.m.  Could we use that?

If that's not acceptable, I agree then that your suggestion is better than my change to configure - so I'll scrap it and implement your suggested change.

**Comment by b4winckler** [comment]
I did not write the icon generation program but as far as I can remember the Envy Code R font was chosen because it looked best that small.  Simply changing to a stock font will probably make things uglier.

If you have time to find a stock font that looks good at tiny size, then I think it would be nice if we could fall back on a stock font if ECR is missing (but to still use ECR if it is present).  Note that MacVim supports OS X 10.4 and up so the font should be available on all supported versions.

**Comment by levifig** [comment]
Related: MacVim is failing to build because the EnvyCodeR font is not available at the requested URL (http://download.damieng.com/latest/EnvyCodeR is giving a HTTP 500 error). Maybe we should mirror that file somewhere else or update the link to the one in his blog post (http://download.damieng.com/fonts/original/EnvyCodeR-PR7.zip). I tried this and everything compiled fine.

**Comment by b4winckler** [comment]
Thanks.  I updated the URL for now.  We really need to make the dependency on ECR optional.

**Comment by levifig** [comment]
Indeed. Glad I could help.

**Comment by humblehacker** [comment]
I've submitted a patch on the issue tracker to make ECR optional.

**Pull request closed without merging**
