### PR TITLE
Fix getfontname().

### PR DESCRIPTION
**Pull request by jszakmeister**
getfontname() would incorrectly return strings of the form
"FONTNAME:SIZE", when it should be returning strings of the form
"FONTNAME:hSIZE"--notice the "h" in the last form.  However, the
internal font string needs to maintain the first form.  So, instead we
cut it up and insert the "h" in the proper location giving it the proper
form.

### CODE REVIEW

**Comment by jszakmeister** [comment]
Björn, I'm not sure that this is the proper way to make the fix (there might be a better way to do it).  However, it does fix the issue I was seeing.  Namely, that MacVim would not work correctly with the Dr. Mike's [fontsize plugin](https://github.com/drmikehenry/vim-fontsize).  I know there are other hotkeys in MacVim to adjust the font size, but I use Vim on several platforms, so it's helpful to have this work correctly.

BTW, thank you very much for MacVim--it's fantastic!

**Comment by b4winckler** [comment]
Thanks for the patch.

I had a quick look and I believe the "right" fix would instead be to include the "h" in the font name when it is stored internally (it might require some thought/testing).  This should be achievable by fixing `gui_macvim_font_with_name()` in two places (`"%@:%d"` should be `"%@:h%d"`), and fixing `-[MMBackend setFont:]` so that the size component removes the "h" before calling `floatValue`.

Can you test this and see if it works?

**Comment by jszakmeister** [comment]
Thanks for the feedback Björn.  I'll take a look at that approach.  I should have some time a little later today, so I'll try and get back to you by then.

**Comment by jszakmeister** [comment]
So I had some free time waiting for something else to finish.  Here's an updated patch with your suggestion.  I did try it out and it appears to work correctly.

**Comment by b4winckler** [comment]
Thanks!  I think that will do it so I've pushed your patch, but please keep a lookout and let me know if you find any problems.

**Comment by jszakmeister** [comment]
Will do.  Thanks!

**Pull request closed without merging**
