### PR TITLE
activate localizations

### PR DESCRIPTION
**Pull request by youknowone**
activate localizations copied to runtime/lang/*/LC_MESSAGES

it just works for macports only currently.

### CODE REVIEW

**Comment by b4winckler** [comment]
Please explain in more detail what this commit does.

**Comment by youknowone** [comment]
macvim does not contain gettext localization files now.
macvim have code in main.c
            vim_snprintf((char *)NameBuff, MAXPATHL, "%s/lang", p);
            bindtextdomain(VIMPACKAGE, (char *)NameBuff);
so i've added generating code for localization files.
you can find it in runtime/lang after runtime/lang/(locale)/LC_MESSAGES
this files make macvim load gettext localization

it don't work itself for your project (i don't know why)
but it works for your macport Portfile

**Comment by b4winckler** [comment]
I think all you need is libintl in order to get translated messages in Vim.  As far as I can tell your patch is unnecessary. (?)

Also, localizing MacVim requires a lot more effort than this -- there are new menu items and also some dialogs that need translating.  I've started working on this but have not yet have had time to finish it.

**Comment by youknowone** [comment]
your macport binary is ready for nls but do not have the files i generated.
if it is true as you say, your macport binary should have that files already, but not.

i am not good at unix configure, so i failed to find it in configure.

i am trying to combine precompiled libintl to project... if it success, it will say generation is required or not

and another something that i am trying is auto-generated xib from gettext messages.
though it could not cover whole messages, i got half of success to reduce manual localization process in other project.
see http://github.com/ToePeu/xchat-aqua/tree/master/tools/localization/

i'll start this work after success to activating gettext in macvim

**Comment by b4winckler** [comment]
Sorry, I don't have anything to do with MacPorts.  You should talk to the port maintainer about that (I don't know who this is).

If you want to enable gettext with MacVim (that I am maintaining) you only need to make sure libintl is installed and can be found by configure.

Maybe I'm not getting the full picture?

**Comment by youknowone** [comment]
I am sorry for confusing. forget about macports. it is just a sympton not a cause.

Please compare build result of mine and yours

I configured with this option for my repo
CFLAGS="-I$PWD/MacVim/include" LDFLAGS="-L$PWD/MacVim/lib -lintl -liconv2 -framework Cocoa" ./configure --with-features=huge  --enable-rubyinterp   --enable-pythoninterp  --enable-perlinterp --enable-cscope --enable-multibyte

Mine run valid localized vim, but not yours do. Because your one does not have LC_MESSAGES in runtime/lang.

I just added it to binary. I think libintl should work for it as you say. but don't know why it don't include it in binary.

Anything else i missed? Or do you know how to resolve this problem?

**Comment by youknowone** [comment]
I got all things now... this is just explaining. take some if you need or just resolve #3 please.

this commits include next things
1. rename nib and its directory. this have no change for current version. so dropping this do not affect others. I expect i can derive some localizations for MacVim from original vim gettext, but cannot sure. if i fail to this job, this commits are meaningless. I should not contains this files to this pull request.
2. include precompiled libiconv and libintl for 10.5 and 10.6 for ppc/i386/x86_64. this will be helpful for users do not have their own libraries and ensure unique library link. but not nessessary for --disable-nls users
3. Add bash script for xcode to copy generated gettext files to runtime. (locale).mo files are in macvim/src/po and not copied to runtime currently. I think there should be a way to copy this files to binary. This script is just a workaround because i don't know well about unix developement environment.

Thank you!

**Comment by b4winckler** [comment]
Ok.  I understand what the problem is now.  Thanks for the explanation.

However, I don't want to merge any localization stuff into mainline at this point in time -- but please keep working on it.

By the way, have you checked out the macvim-kaoriya project?  I'm guessing they had to do something similar already...

**Comment by cooljeanius** [comment]
> Sorry, I don't have anything to do with MacPorts. You should talk to the port maintainer about that (I don't know who this is).

That's @raimue (Rainer Müller)

**Pull request closed without merging**
